In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import os
os.chdir(os.getcwd())
from sklearn.metrics import accuracy_score

In [2]:
os.getcwd()

'/home/nabil/Dev/treehouse/ForkRiboVsPolyA/RiboVsPolyA/examples'

In [3]:
DEPTH=3

# Random Forrest Results

## Using Treehouse Pipeline

In [4]:
srp_tpm_df = pd.read_csv("../results/SRP026013_TPM_log2_plus_1.TH.balanced_maxdepth%d_results.tsv"%DEPTH, index_col=0, sep='\t')

In [5]:
srp_tpm_df.shape

(8, 3)

In [6]:
samples_of_int =srp_tpm_df.index

In [7]:
true_labels = np.array([0]*srp_tpm_df.shape[0])
pred_labels = srp_tpm_df.Ribo.values
pred_proba = srp_tpm_df.Proba_1.values

In [8]:
true_labels

array([0, 0, 0, 0, 0, 0, 0, 0])

In [9]:
pred_labels

array([0., 0., 0., 0., 0., 0., 0., 0.])

In [10]:
pred_proba

array([0.04375866, 0.04875866, 0.06042533, 0.06371171, 0.06000866,
       0.07537582, 0.05375866, 0.04375866])

In [11]:
acc= accuracy_score(true_labels,pred_labels)
print('Accuracy: {}'.format(acc))

Accuracy: 1.0


## Using refine.bio Pipeline

In [10]:
srp_tpm_df = pd.read_csv("../results/SRP026013_TPM_log2_plus_1.balanced_maxdepth%d_results.tsv"%DEPTH, index_col=0, sep='\t')

In [11]:
old_index = srp_tpm_df.index
new_index = [x.split('_')[0] for x in old_index]
rename_dict = dict(zip(old_index, new_index))

srp_tpm_df = srp_tpm_df.rename(index=rename_dict)

In [12]:
srp_tpm_df = srp_tpm_df.loc[samples_of_int]

In [13]:
true_labels = np.array([0]*srp_tpm_df.shape[0])
pred_labels = srp_tpm_df.Ribo.values
pred_proba = srp_tpm_df.Proba_1.values

In [16]:
acc= accuracy_score(true_labels,pred_labels)
print('Accuracy: {}'.format(acc))

Accuracy: 1.0


# Logistic Regression Results

In [14]:
srp_tpm_df = pd.read_csv("../results/SRP026013_TPM_log2_plus_1.balanced_Logistic_results.tsv", index_col=0, sep='\t')

In [15]:
true_labels = np.array([0]*srp_tpm_df.shape[0])
pred_labels = srp_tpm_df.Ribo.values
pred_proba = srp_tpm_df.Proba_1.values

In [16]:
acc= accuracy_score(true_labels,pred_labels)
print('Accuracy: {}'.format(acc))

Accuracy: 0.9375
