In [17]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import os
os.chdir(os.getcwd())
from evaluate import classification_eval

In [18]:
os.getcwd()

'/mnt/github/RiboVsPolyA/examples'

In [19]:
DEPTH=3

## Using Treehouse Pipeline

In [20]:
srp_tpm_df = pd.read_csv("../results/SRP026013_TPM_log2_plus_1.TH.balanced_maxdepth%d_results.tsv"%DEPTH, index_col=0, sep='\t')

In [21]:
srp_tpm_df.shape

(8, 3)

In [22]:
samples_of_int =srp_tpm_df.index

In [23]:
true_labels = np.array([0]*srp_tpm_df.shape[0])
pred_labels = srp_tpm_df.Ribo.values
pred_proba = srp_tpm_df.Proba_1.values

In [24]:
true_labels

array([0, 0, 0, 0, 0, 0, 0, 0])

In [25]:
pred_labels

array([0., 0., 0., 0., 0., 0., 0., 0.])

In [26]:
pred_proba

array([0.04375866, 0.04875866, 0.06042533, 0.06371171, 0.06000866,
       0.07537582, 0.05375866, 0.04375866])

In [28]:
acc, f1, roc_auc = classification_eval(true_labels,pred_labels,pred_proba)
print('Accuracy: {}\nF1-score: {}'.format(acc, f1))

IndexError: arrays used as indices must be of integer (or boolean) type

<Figure size 720x720 with 0 Axes>

## Using refine.bio Pipeline

In [29]:
srp_tpm_df = pd.read_csv("../results/SRP026013_TPM_log2_plus_1.balanced_maxdepth%d_results.tsv"%DEPTH, index_col=0, sep='\t')

In [30]:
old_index = srp_tpm_df.index
new_index = [x.split('_')[0] for x in old_index]
rename_dict = dict(zip(old_index, new_index))

srp_tpm_df = srp_tpm_df.rename(index=rename_dict)

In [31]:
srp_tpm_df = srp_tpm_df.loc[samples_of_int]

In [32]:
true_labels = np.array([0]*srp_tpm_df.shape[0])
pred_labels = srp_tpm_df.Ribo.values
pred_proba = srp_tpm_df.Proba_1.values

In [33]:
acc, f1, roc_auc, precision= classification_eval(true_labels,pred_labels,pred_proba, classes=[0,1])
print('Accuracy: {}\nF1-score: {}'.format(acc, f1))

TypeError: classification_eval() got multiple values for argument 'classes'