In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import os
os.chdir(os.getcwd())
from sklearn.metrics import accuracy_score

In [2]:
os.getcwd()

'/home/nabil/Dev/treehouse/ForkRiboVsPolyA/RiboVsPolyA/examples'

In [3]:
DEPTH=3

# Random Forest Results

## Using Treehouse Pipeline

In [4]:
srp_tpm_df = pd.read_csv("../results/SRP064410_TPM_log2_plus_1.TH.balanced_maxdepth%d_results.tsv"%DEPTH, index_col=0, sep='\t')

In [5]:
srp_tpm_df.shape

(10, 3)

In [6]:
true_labels = np.array([0]*srp_tpm_df.shape[0])
pred_labels = srp_tpm_df.Ribo.values
pred_proba = srp_tpm_df.Proba_1.values

In [7]:
true_labels

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [8]:
pred_labels

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [9]:
pred_proba

array([0.03909671, 0.04903857, 0.03909671, 0.05909671, 0.04909671,
       0.03909671, 0.05896096, 0.04009671, 0.03909671, 0.06894333])

In [10]:
acc= accuracy_score(true_labels,pred_labels)
print('Accuracy: {}'.format(acc))

Accuracy: 1.0


## Using refine.bio Pipeline

In [13]:
srp_tpm_df = pd.read_csv("../results/SRP064410_TPM_log2_plus_1.balanced_maxdepth%d_results.tsv"%DEPTH, index_col=0, sep='\t')

FileNotFoundError: [Errno 2] No such file or directory: '../results/SRP064410_TPM_log2_plus_1.balanced_maxdepth3_results.tsv'

In [14]:
srp_tpm_df.shape

(10, 3)

In [15]:
true_labels = np.array([0]*srp_tpm_df.shape[0])
pred_labels = srp_tpm_df.Ribo.values
pred_proba = srp_tpm_df.Proba_1.values

In [16]:
acc= accuracy_score(true_labels,pred_labels)
print('Accuracy: {}'.format(acc))

Accuracy: 1.0


# Logistic Regression Results

In [17]:
srp_tpm_df = pd.read_csv("../results/SRP064410_TPM_log2_plus_1.TH.balanced_Logistic_results.tsv", index_col=0, sep='\t')

In [18]:
true_labels = np.array([0]*srp_tpm_df.shape[0])
pred_labels = srp_tpm_df.Ribo.values
pred_proba = srp_tpm_df.Proba_1.values

In [19]:
acc= accuracy_score(true_labels,pred_labels)
print('Accuracy: {}'.format(acc))

Accuracy: 1.0
