In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import os
os.chdir(os.getcwd())
from sklearn.metrics import accuracy_score

In [2]:
os.getcwd()

'/mnt/github/RiboVsPolyA/examples'

In [3]:
DEPTH=3

## Using Treehouse Pipeline

In [4]:
srp_tpm_df = pd.read_csv("../results/SRP058841_TPM_log2_plus_1.TH.balanced_maxdepth%d_results.tsv"%DEPTH, index_col=0, sep='\t')

In [5]:
srp_tpm_df.shape

(18, 3)

In [6]:
true_labels = np.array([1]*srp_tpm_df.shape[0])
pred_labels = srp_tpm_df.Ribo.values
pred_proba = srp_tpm_df.Proba_1.values

In [7]:
true_labels

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

In [8]:
pred_labels

array([1., 1., 1., 1., 1., 0., 0., 0., 1., 1., 1., 1., 0., 0., 0., 0., 0.,
       1.])

In [9]:
pred_proba

array([0.70776096, 0.68207334, 0.62697656, 0.58973156, 0.53008447,
       0.41068659, 0.41068446, 0.34389274, 0.50725011, 0.64397758,
       0.67192008, 0.51220302, 0.43273632, 0.3543445 , 0.3368209 ,
       0.21683187, 0.2941326 , 0.63735891])

In [10]:
acc= accuracy_score(true_labels,pred_labels)
print('Accuracy: {}'.format(acc))

Accuracy: 0.5555555555555556


## Using refine.bio Pipeline

In [11]:
srp_tpm_df = pd.read_csv("../results/SRP058841_TPM_log2_plus_1.balanced_maxdepth%d_results.tsv"%DEPTH, index_col=0, sep='\t')

In [12]:
srp_tpm_df.shape

(18, 3)

In [13]:
true_labels = np.array([1]*srp_tpm_df.shape[0])
pred_labels = srp_tpm_df.Ribo.values
pred_proba = srp_tpm_df.Proba_1.values

In [14]:
acc= accuracy_score(true_labels,pred_labels)
print('Accuracy: {}'.format(acc))

Accuracy: 0.8888888888888888
