In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import os
os.chdir(os.getcwd())
from sklearn.metrics import accuracy_score

In [3]:
os.getcwd()

'/home/nabil/Dev/treehouse/ForkRiboVsPolyA/RiboVsPolyA/examples'

In [4]:
DEPTH=3

# Random Forest Results

## Using Treehouse Pipeline

In [5]:
srp_tpm_df = pd.read_csv("../results/SRP055411_TPM_log2_plus_1.balanced_maxdepth%d_results.tsv"%DEPTH, index_col=0, sep='\t')

In [6]:
srp_tpm_df.shape

(11, 3)

In [7]:
true_labels = np.array([1]*srp_tpm_df.shape[0])
pred_labels = srp_tpm_df.Ribo.values
pred_proba = srp_tpm_df.Proba_1.values

In [8]:
true_labels

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

In [9]:
pred_labels

array([1., 1., 1., 1., 1., 1., 0., 1., 1., 1., 1.])

In [10]:
pred_proba

array([0.58127214, 0.52550998, 0.51504053, 0.51990823, 0.54581316,
       0.51171216, 0.49986813, 0.53506813, 0.56541174, 0.51970646,
       0.53091598])

In [11]:
acc= accuracy_score(true_labels,pred_labels)
print('Accuracy: {}'.format(acc))

Accuracy: 0.9090909090909091


## Using refine.bio Pipeline

In [12]:
srp_tpm_df = pd.read_csv("../results/SRP055411_TPM_log2_plus_1.balanced_maxdepth%d_results.tsv"%DEPTH, index_col=0, sep='\t')

In [13]:
srp_tpm_df.shape

(11, 3)

In [14]:
true_labels = np.array([1]*srp_tpm_df.shape[0])
pred_labels = srp_tpm_df.Ribo.values
pred_proba = srp_tpm_df.Proba_1.values

In [15]:
acc= accuracy_score(true_labels,pred_labels)
print('Accuracy: {}'.format(acc))

Accuracy: 0.9090909090909091


# Logistic Regression Results

In [20]:
srp_tpm_df = pd.read_csv("../results/SRP055411_TPM_log2_plus_1.balanced_Logistic_results.tsv", index_col=0, sep='\t')

In [21]:
true_labels = np.array([0]*srp_tpm_df.shape[0])
pred_labels = srp_tpm_df.Ribo.values
pred_proba = srp_tpm_df.Proba_1.values

In [22]:
acc= accuracy_score(true_labels,pred_labels)
print('Accuracy: {}'.format(acc))

Accuracy: 0.0
