In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import os
os.chdir(os.getcwd())
from sklearn.metrics import accuracy_score

In [2]:
os.getcwd()

'/home/nabil/Dev/treehouse/ForkRiboVsPolyA/RiboVsPolyA/examples'

In [3]:
DEPTH=3

# Random Forest Results

## Using treehouse pipeline

In [4]:
srp_tpm_df = pd.read_csv("../results/SRP132968_TPM_log2_plus_1.TH.balanced_maxdepth%d_results.tsv"%DEPTH, index_col=0, sep='\t')

In [5]:
srp_tpm_df.shape

(57, 3)

In [6]:
true_labels = np.array([0]*srp_tpm_df.shape[0])
pred_labels = srp_tpm_df.Ribo.values
pred_proba = srp_tpm_df.Proba_1.values

In [7]:
true_labels

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [8]:
pred_labels

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0.])

In [9]:
pred_proba

array([0.05645767, 0.06110396, 0.08214046, 0.08975449, 0.0994738 ,
       0.14889597, 0.0794924 , 0.08074659, 0.09288081, 0.08079574,
       0.08081998, 0.06104695, 0.12912415, 0.10051843, 0.09740251,
       0.1014389 , 0.06966536, 0.05968091, 0.14099132, 0.09068845,
       0.11733774, 0.07220382, 0.10172499, 0.05981154, 0.0768244 ,
       0.06111973, 0.06194492, 0.07173318, 0.04094492, 0.08747826,
       0.09948278, 0.10287995, 0.12938619, 0.05776337, 0.10926735,
       0.08076179, 0.05976769, 0.07104695, 0.07104695, 0.06966536,
       0.09613604, 0.04210396, 0.09955671, 0.11919746, 0.11173428,
       0.09188012, 0.06968791, 0.10218923, 0.1093233 , 0.07948278,
       0.04109954, 0.09629281, 0.1019166 , 0.09077525, 0.08086488,
       0.10332592, 0.07083622])

In [10]:
acc= accuracy_score(true_labels,pred_labels)
print('Accuracy: {}'.format(acc))

Accuracy: 1.0


## refine.bio pipeline

In [11]:
srp_tpm_df = pd.read_csv("../results/SRP132968_TPM_log2_plus_1.balanced_maxdepth%d_results.tsv"%DEPTH, index_col=0, sep='\t')
true_labels = np.array([0]*srp_tpm_df.shape[0])
pred_labels = srp_tpm_df.Ribo.values
pred_proba = srp_tpm_df.Proba_1.values
acc= accuracy_score(true_labels,pred_labels)
print('Accuracy: {}'.format(acc))

Accuracy: 1.0


# Logistic Regression Results

In [12]:
srp_tpm_df = pd.read_csv("../results/SRP132968_TPM_log2_plus_1.TH.balanced_Logistic_results.tsv", index_col=0, sep='\t')

In [13]:
true_labels = np.array([0]*srp_tpm_df.shape[0])
pred_labels = srp_tpm_df.Ribo.values
pred_proba = srp_tpm_df.Proba_1.values

In [14]:
acc= accuracy_score(true_labels,pred_labels)
print('Accuracy: {}'.format(acc))

Accuracy: 1.0
