In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import os
os.chdir(os.getcwd())
from sklearn.metrics import accuracy_score

In [2]:
os.getcwd()

'/home/nabil/Dev/treehouse/ForkRiboVsPolyA/RiboVsPolyA/examples'

In [3]:
DEPTH=3

# Random Forest Results

## Using Treehouse Pipeline

In [4]:
srp_tpm_df = pd.read_csv("../results/SRP109549_TPM_log2_plus_1.TH.balanced_maxdepth%d_results.tsv"%DEPTH, index_col=0, sep='\t')

In [5]:
srp_tpm_df.shape

(74, 3)

In [6]:
true_labels = np.array([1]*srp_tpm_df.shape[0])
pred_labels = srp_tpm_df.Ribo.values
pred_proba = srp_tpm_df.Proba_1.values

In [7]:
true_labels

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1])

In [8]:
np.where(pred_labels==0)[0]

array([ 8, 18])

In [9]:
srp_tpm_df.iloc[45]

Ribo       1.000000
Proba_0    0.321133
Proba_1    0.678867
Name: SRR5693376, dtype: float64

In [10]:
pred_proba

array([0.82983727, 0.87845316, 0.85704854, 0.59765675, 0.59999325,
       0.7489686 , 0.69964814, 0.55999372, 0.46995341, 0.51036098,
       0.51008788, 0.74103733, 0.77938893, 0.78985423, 0.77718978,
       0.78896567, 0.82743755, 0.80743468, 0.44033293, 0.55013859,
       0.60955237, 0.55965977, 0.79004259, 0.82789333, 0.82709416,
       0.86699804, 0.74943346, 0.73933524, 0.79746786, 0.76751383,
       0.63961176, 0.60979278, 0.61989407, 0.58985605, 0.57027785,
       0.53009641, 0.75987067, 0.88704854, 0.83843481, 0.88704854,
       0.87924453, 0.8287983 , 0.76739342, 0.75003733, 0.76853118,
       0.67886722, 0.73121732, 0.76126803, 0.79878995, 0.7494341 ,
       0.82055495, 0.82130753, 0.66946649, 0.54785807, 0.54831158,
       0.69865164, 0.81079806, 0.8408804 , 0.66382531, 0.67157579,
       0.58799899, 0.78929157, 0.71026823, 0.64257831, 0.55180345,
       0.59965661, 0.56971159, 0.85709527, 0.76878877, 0.80699804,
       0.84655014, 0.81865504, 0.79902204, 0.71907255])

In [11]:
acc= accuracy_score(true_labels,pred_labels)
print('Accuracy: {}'.format(acc))

Accuracy: 0.972972972972973


## Using refine.bio Pipeline

In [12]:
srp_tpm_df = pd.read_csv("../results/SRP109549_TPM_log2_plus_1.balanced_maxdepth%d_results.tsv"%DEPTH, index_col=0, sep='\t')

In [13]:
srp_tpm_df.shape

(74, 3)

In [14]:
true_labels = np.array([1]*srp_tpm_df.shape[0])
pred_labels = srp_tpm_df.Ribo.values
pred_proba = srp_tpm_df.Proba_1.values

In [15]:
pred_proba[45]

0.8273357610966104

In [16]:
acc= accuracy_score(true_labels,pred_labels)
print('Accuracy: {}'.format(acc))

Accuracy: 1.0


# Logistic Regression Results

In [17]:
srp_tpm_df = pd.read_csv("../results/SRP109549_TPM_log2_plus_1.TH.balanced_Logistic_results.tsv", index_col=0, sep='\t')

In [18]:
true_labels = np.array([0]*srp_tpm_df.shape[0])
pred_labels = srp_tpm_df.Ribo.values
pred_proba = srp_tpm_df.Proba_1.values

In [19]:
acc= accuracy_score(true_labels,pred_labels)
print('Accuracy: {}'.format(acc))

Accuracy: 0.0
