In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import os
os.chdir(os.getcwd())
from sklearn.metrics import accuracy_score

In [2]:
os.getcwd()

'/home/nabil/Dev/treehouse/RiboVsPolyA/examples'

In [3]:
DEPTH=3

# Random Forest Results

## Using Treehouse Pipeline

In [4]:
srp_tpm_df = pd.read_csv("../results/SRP183700_TPM_log2_plus_1.TH.balanced_maxdepth%d_results.tsv"%DEPTH, index_col=0, sep='\t')

In [5]:
srp_tpm_df.shape

(30, 3)

In [6]:
true_labels = np.array([1]*srp_tpm_df.shape[0])
pred_labels = srp_tpm_df.Ribo.values
pred_proba = srp_tpm_df.Proba_1.values

In [7]:
true_labels

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1])

In [8]:
pred_labels

array([1., 0., 1., 1., 1., 1., 1., 1., 1., 1., 1., 0., 0., 1., 0., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [9]:
pred_proba

array([0.69015504, 0.46089455, 0.63088745, 0.64074745, 0.70017737,
       0.57995116, 0.61074431, 0.76767312, 0.61993036, 0.54042538,
       0.51078168, 0.48072279, 0.48085782, 0.6300087 , 0.49095479,
       0.50065854, 0.73797065, 0.73802651, 0.57849418, 0.52030517,
       0.81723731, 0.81869193, 0.71797402, 0.56083616, 0.57084402,
       0.65036856, 0.75777892, 0.70767482, 0.60068279, 0.6481801 ])

In [10]:
acc= accuracy_score(true_labels,pred_labels)
print('Accuracy: {}'.format(acc))

Accuracy: 0.8666666666666667


## Using refine.bio Pipeline

In [11]:
srp_tpm_df = pd.read_csv("../results/SRP183700_TPM_log2_plus_1.balanced_maxdepth%d_results.tsv"%DEPTH, index_col=0, sep='\t')

In [12]:
srp_tpm_df.shape

(30, 3)

In [13]:
true_labels = np.array([1]*srp_tpm_df.shape[0])
pred_labels = srp_tpm_df.Ribo.values
pred_proba = srp_tpm_df.Proba_1.values

In [14]:
acc= accuracy_score(true_labels,pred_labels)
print('Accuracy: {}'.format(acc))

Accuracy: 0.9333333333333333


# Logistic Regression Results

In [15]:
srp_tpm_df = pd.read_csv("../results/SRP183700_TPM_log2_plus_1.TH.balanced_Logistic_results.tsv", index_col=0, sep='\t')

In [16]:
true_labels = np.array([0]*srp_tpm_df.shape[0])
pred_labels = srp_tpm_df.Ribo.values
pred_proba = srp_tpm_df.Proba_1.values

In [17]:
acc= accuracy_score(true_labels,pred_labels)
print('Accuracy: {}'.format(acc))

Accuracy: 0.0
