In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import os
os.chdir(os.getcwd())
from sklearn.metrics import accuracy_score

In [2]:
os.getcwd()

'/mnt/github/RiboVsPolyA/examples'

In [3]:
DEPTH=3

## Using Treehouse Pipeline

In [4]:
srp_tpm_df = pd.read_csv("../results/SRP109549_TPM_log2_plus_1.TH.balanced_maxdepth%d_results.tsv"%DEPTH, index_col=0, sep='\t')

In [5]:
srp_tpm_df.shape

(74, 3)

In [6]:
true_labels = np.array([1]*srp_tpm_df.shape[0])
pred_labels = srp_tpm_df.Ribo.values
pred_proba = srp_tpm_df.Proba_1.values

In [7]:
true_labels

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1])

In [8]:
np.where(pred_labels==0)[0]

array([ 3, 18, 19, 53, 54, 64])

In [9]:
srp_tpm_df.iloc[45]

Ribo       1.000000
Proba_0    0.234886
Proba_1    0.765114
Name: SRR5693376, dtype: float64

In [10]:
pred_proba

array([0.89493221, 0.94443069, 0.91457503, 0.49650115, 0.52644465,
       0.715706  , 0.66630768, 0.51631261, 0.50690439, 0.51699979,
       0.54670506, 0.82521674, 0.7657017 , 0.78556129, 0.85506384,
       0.85488202, 0.87602636, 0.86983456, 0.44701963, 0.47693363,
       0.5865581 , 0.55664943, 0.83512149, 0.86493221, 0.89484135,
       0.92464275, 0.84501009, 0.81544723, 0.85530377, 0.76540833,
       0.60631355, 0.5965067 , 0.5767072 , 0.56659813, 0.50846794,
       0.52680833, 0.71594509, 0.92932598, 0.87488001, 0.93432598,
       0.90482847, 0.89596425, 0.84477826, 0.85486769, 0.83492476,
       0.76511386, 0.82499316, 0.85492511, 0.87962615, 0.85962615,
       0.87621831, 0.85513564, 0.62626267, 0.40699741, 0.4170929 ,
       0.53628622, 0.85628174, 0.85619592, 0.73544663, 0.72544345,
       0.73525344, 0.81501632, 0.80501328, 0.55583038, 0.43701212,
       0.52655955, 0.58654369, 0.91463859, 0.89478871, 0.91442307,
       0.94432598, 0.84021751, 0.71591004, 0.6459641 ])

In [11]:
acc= accuracy_score(true_labels,pred_labels)
print('Accuracy: {}'.format(acc))

Accuracy: 0.918918918918919


## Using refine.bio Pipeline

In [12]:
srp_tpm_df = pd.read_csv("../results/SRP109549_TPM_log2_plus_1.balanced_maxdepth%d_results.tsv"%DEPTH, index_col=0, sep='\t')

In [13]:
srp_tpm_df.shape

(74, 3)

In [14]:
true_labels = np.array([1]*srp_tpm_df.shape[0])
pred_labels = srp_tpm_df.Ribo.values
pred_proba = srp_tpm_df.Proba_1.values

In [15]:
pred_proba[45]

0.8352027452061528

In [16]:
acc= accuracy_score(true_labels,pred_labels)
print('Accuracy: {}'.format(acc))

Accuracy: 1.0
