In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import os
os.chdir(os.getcwd())
from sklearn.metrics import accuracy_score

In [2]:
os.getcwd()

'/mnt/github/RiboVsPolyA/examples'

In [3]:
DEPTH=3

## Using Treehouse Pipeline

In [4]:
srp_tpm_df = pd.read_csv("../results/SRP130971_TPM_log2_plus_1.TH.balanced_maxdepth%d_results.tsv"%DEPTH, index_col=0, sep='\t')

In [5]:
srp_tpm_df.shape

(12, 3)

In [6]:
true_labels = np.array([1]*srp_tpm_df.shape[0])
pred_labels = srp_tpm_df.Ribo.values
pred_proba = srp_tpm_df.Proba_1.values

In [7]:
true_labels

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

In [8]:
pred_labels

array([0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0.])

In [9]:
pred_proba

array([0.46251589, 0.40179657, 0.39550607, 0.34966852, 0.52643274,
       0.4665294 , 0.43274109, 0.4053609 , 0.40919154, 0.49874037,
       0.39549495, 0.3797183 ])

In [10]:
acc= accuracy_score(true_labels,pred_labels)
print('Accuracy: {}'.format(acc))

Accuracy: 0.08333333333333333


## Using refine.bio Pipeline

In [11]:
srp_tpm_df = pd.read_csv("../results/SRP130971_TPM_log2_plus_1.balanced_maxdepth%d_results.tsv"%DEPTH, index_col=0, sep='\t')

In [12]:
srp_tpm_df.shape

(12, 3)

In [13]:
true_labels = np.array([1]*srp_tpm_df.shape[0])
pred_labels = srp_tpm_df.Ribo.values
pred_proba = srp_tpm_df.Proba_1.values

In [14]:
acc= accuracy_score(true_labels,pred_labels)
print('Accuracy: {}'.format(acc))

Accuracy: 1.0
