In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import os
os.chdir(os.getcwd())
from sklearn.metrics import accuracy_score

In [2]:
os.getcwd()

'/mnt/github/RiboVsPolyA/examples'

In [3]:
DEPTH=3

## Using Treehouse Pipeline

In [4]:
srp_tpm_df = pd.read_csv("../results/SRP183700_TPM_log2_plus_1.TH.balanced_maxdepth%d_results.tsv"%DEPTH, index_col=0, sep='\t')

In [5]:
srp_tpm_df.shape

(30, 3)

In [6]:
true_labels = np.array([1]*srp_tpm_df.shape[0])
pred_labels = srp_tpm_df.Ribo.values
pred_proba = srp_tpm_df.Proba_1.values

In [7]:
true_labels

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1])

In [8]:
pred_labels

array([1., 0., 1., 1., 1., 0., 1., 1., 1., 1., 0., 0., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [9]:
pred_proba

array([0.67706856, 0.46984931, 0.64750176, 0.63741085, 0.65717063,
       0.4980663 , 0.58766514, 0.71716402, 0.61750539, 0.54796748,
       0.4897872 , 0.48806213, 0.50791597, 0.59620694, 0.51817177,
       0.52785219, 0.78668475, 0.78647918, 0.57770442, 0.52794342,
       0.89604537, 0.8661916 , 0.76547061, 0.55785884, 0.5379096 ,
       0.61749514, 0.82503501, 0.68587258, 0.56656297, 0.74647888])

In [10]:
acc= accuracy_score(true_labels,pred_labels)
print('Accuracy: {}'.format(acc))

Accuracy: 0.8666666666666667


## Using refine.bio Pipeline

In [11]:
srp_tpm_df = pd.read_csv("../results/SRP183700_TPM_log2_plus_1.balanced_maxdepth%d_results.tsv"%DEPTH, index_col=0, sep='\t')

In [12]:
srp_tpm_df.shape

(30, 3)

In [13]:
true_labels = np.array([1]*srp_tpm_df.shape[0])
pred_labels = srp_tpm_df.Ribo.values
pred_proba = srp_tpm_df.Proba_1.values

In [14]:
acc= accuracy_score(true_labels,pred_labels)
print('Accuracy: {}'.format(acc))

Accuracy: 1.0
