In [11]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import os
os.chdir(os.getcwd())
from eval import classification_eval

In [2]:
os.getcwd()

'/mnt/github/RiboVsPolyA/examples'

In [3]:
DEPTH=3

In [4]:
srp_tpm_df = pd.read_csv("../results/SRP132968_TPM_log2_plus_1.TH.balanced_maxdepth%d_results.tsv"%DEPTH, index_col=0, sep='\t')

In [5]:
srp_tpm_df.shape

(57, 3)

In [6]:
true_labels = np.array([0]*srp_tpm_df.shape[0])
pred_labels = srp_tpm_df.Ribo.values
pred_proba = srp_tpm_df.Proba_1.values

In [7]:
true_labels

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [8]:
pred_labels

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0.])

In [9]:
pred_proba

array([0.0799579 , 0.05000866, 0.07042533, 0.10986611, 0.06000866,
       0.0699579 , 0.04000866, 0.09639984, 0.07167533, 0.05662457,
       0.08652094, 0.10000866, 0.08662457, 0.05667533, 0.0914506 ,
       0.10991095, 0.0999579 , 0.0899579 , 0.08000866, 0.07991095,
       0.06505291, 0.08542533, 0.11973317, 0.0699579 , 0.08500866,
       0.09000866, 0.11657762, 0.04996171, 0.09851813, 0.08000866,
       0.0899579 , 0.08000866, 0.11829123, 0.0799579 , 0.0799579 ,
       0.09991306, 0.07667533, 0.07662457, 0.07500866, 0.11644679,
       0.09667533, 0.05667533, 0.06000866, 0.09996171, 0.08162457,
       0.22929768, 0.08496171, 0.08375866, 0.09162457, 0.07000866,
       0.09662457, 0.08662457, 0.09329505, 0.04000866, 0.03000866,
       0.06000866, 0.06537838])

In [15]:
acc, f1, roc_auc, precision= classification_eval(true_labels,pred_labels,pred_proba, classes=[0,1])
print('Accuracy: {}\nF1-score: {}\nROC_AUC: {}'.format(acc, f1, roc_auc))

TypeError: classification_eval() got multiple values for argument 'classes'

## refine.bio pipeline

In [ ]:
srp_tpm_df = pd.read_csv("../results/SRP132968_TPM_log2_plus_1.balanced_maxdepth%d_results.tsv"%DEPTH, index_col=0, sep='\t')
true_labels = np.array([0]*srp_tpm_df.shape[0])
pred_labels = srp_tpm_df.Ribo.values
pred_proba = srp_tpm_df.Proba_1.values
acc, f1, roc_auc, precision= classification_eval(true_labels,pred_labels,pred_proba, classes=[0,1])
print('Accuracy: {}\nF1-score: {}\nROC_AUC: {}'.format(acc, f1, roc_auc))